kind: pipeline
name: test-go-1.7

steps:
- name: test
  image: golang:1.7
  commands:
  - go get
  - go test

---

kind: pipeline
name: test-go-1.8

steps:
- name: test
  image: golang:1.8
  commands:
  - go get
  - go test

---

kind: pipeline
name: test-go-1.9

steps:
- name: test
  image: golang:1.9
  commands:
  - go get
  - go test

---

kind: pipeline
name: test-go-1.10

steps:
- name: test
  image: golang:1.10
  commands:
  - go get
  - go test

---

kind: pipeline
name: test-go-1.11

steps:
- name: test
  image: golang:1.11
  commands:
  - go get
  - go test

---

kind: pipeline
name: test-go-1.12

steps:
- name: test
  image: golang:1.12
  commands:
  - go get
  - go test

